//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServientregaApi.ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servientrega.com/", ConfigurationName="ServientregaApi.ServiceReference.wsRastreoEnviosSoap")]
    public interface wsRastreoEnviosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/EstadoGuia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.ArrayOfXElement> EstadoGuiaAsync(string ID_Cliente, string guia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGestionEntregas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InfEnvios[]> ConsultarGestionEntregasAsync(string Fecha, string Id_Cliente, string Id_Contacto, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/EstadoGuiasIdDocumentoCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.ArrayOfXElement> EstadoGuiasIdDocumentoClienteAsync(string ID_Cliente, string RelacionDocumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGestionGuias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InfEnvios[]> ConsultarGestionGuiasAsync(string sGuia, string Id_Cliente, string Id_Contacto, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGuia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InformacionGuiaMov> ConsultarGuiaAsync(string NumeroGuia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGuiaImagen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InformacionGuiaMov> ConsultarGuiaImagenAsync(string NumeroGuia, bool BuscarImagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGuiaExterno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InformacionGuiaMov> ConsultarGuiaExternoAsync(string NumeroGuia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/EstadoGuias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.ArrayOfXElement> EstadoGuiasAsync(string ID_Cliente, string RelacionGuias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGestionDevoluciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InfEnvios[]> ConsultarGestionDevolucionesAsync(string Fecha, string Id_Cliente, string Id_Contacto, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ImagenGuia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.ImagenGuiaResponse> ImagenGuiaAsync(ServientregaApi.ServiceReference.ImagenGuiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGuiaPorNumeroReferenciaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InformacionGuiaMov> ConsultarGuiaPorNumeroReferenciaClienteAsync(string Id_Cliente, string Numero_Referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGuiaImagenNovedadesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaImagenNovedadesXMLAsync(string NumeroGuia, int IdProceso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGuiaEvidenciaRTImagenXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaEvidenciaRTImagenXMLAsync(string NumeroGuia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/EstadoGuiaXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EstadoGuiaXMLAsync(string ID_Cliente, string guia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGestionEntregasXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGestionEntregasXMLAsync(string Fecha, string Id_Cliente, string Id_Contacto, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/EstadoGuiasIdDocumentoClienteXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EstadoGuiasIdDocumentoClienteXMLAsync(string ID_Cliente, string RelacionDocumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGestionGuiasXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGestionGuiasXMLAsync(string Guia, string Id_Cliente, string Id_Contacto, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGuiaXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaXMLAsync(string NumeroGuia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGuiaImagenXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaImagenXMLAsync(string NumeroGuia, string BuscarImagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/EstadoGuiasXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EstadoGuiasXMLAsync(string ID_Cliente, string RelacionGuias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGestionDevolucionesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGestionDevolucionesXMLAsync(string Fecha, string Id_Cliente, string Id_Contacto, string Pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarGuiaPorNumeroReferenciaClienteXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaPorNumeroReferenciaClienteXMLAsync(string Id_Cliente, string Numero_Referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultarInfoGuias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarInfoGuiasAsync(string NumerosGuias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/ConsultaGuiasGestionEntregaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultaGuiasGestionEntregaClienteAsync(string Id_Cliente, string Id_Contacto, string Pwd, string FechaInicial, string FechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servientrega.com/FechaEntrega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> FechaEntregaAsync(string NumeroGuia);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servientrega.com/")]
    public partial class MovimientoSrPack
    {
        
        private string descMovField;
        
        private string oriMovField;
        
        private string destMovField;
        
        private string fechMovField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DescMov
        {
            get
            {
                return this.descMovField;
            }
            set
            {
                this.descMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OriMov
        {
            get
            {
                return this.oriMovField;
            }
            set
            {
                this.oriMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DestMov
        {
            get
            {
                return this.destMovField;
            }
            set
            {
                this.destMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FechMov
        {
            get
            {
                return this.fechMovField;
            }
            set
            {
                this.fechMovField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servientrega.com/")]
    public partial class InformacionMov
    {
        
        private int idProcField;
        
        private int idConcField;
        
        private string nomConcField;
        
        private string nomMovField;
        
        private string oriMovField;
        
        private string desMovField;
        
        private string fecMovField;
        
        private int idViewClienteField;
        
        private string tipoMovField;
        
        private string fechaProbField;
        
        private string desTipoMovField;
        
        private string observacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdProc
        {
            get
            {
                return this.idProcField;
            }
            set
            {
                this.idProcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdConc
        {
            get
            {
                return this.idConcField;
            }
            set
            {
                this.idConcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NomConc
        {
            get
            {
                return this.nomConcField;
            }
            set
            {
                this.nomConcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NomMov
        {
            get
            {
                return this.nomMovField;
            }
            set
            {
                this.nomMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OriMov
        {
            get
            {
                return this.oriMovField;
            }
            set
            {
                this.oriMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DesMov
        {
            get
            {
                return this.desMovField;
            }
            set
            {
                this.desMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FecMov
        {
            get
            {
                return this.fecMovField;
            }
            set
            {
                this.fecMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int IdViewCliente
        {
            get
            {
                return this.idViewClienteField;
            }
            set
            {
                this.idViewClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TipoMov
        {
            get
            {
                return this.tipoMovField;
            }
            set
            {
                this.tipoMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FechaProb
        {
            get
            {
                return this.fechaProbField;
            }
            set
            {
                this.fechaProbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DesTipoMov
        {
            get
            {
                return this.desTipoMovField;
            }
            set
            {
                this.desTipoMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servientrega.com/")]
    public partial class InformacionGuiaMov
    {
        
        private string fechaProbableField;
        
        private string numGuiField;
        
        private string fecEnvField;
        
        private int numPieField;
        
        private string ciuRemField;
        
        private string nomRemField;
        
        private string dirRemField;
        
        private string ciuDesField;
        
        private string nomDesField;
        
        private string dirDesField;
        
        private int idEstActField;
        
        private string estActField;
        
        private string fecEstField;
        
        private string nomRecField;
        
        private string numCunField;
        
        private string regimeField;
        
        private string imagenField;
        
        private byte[] bytesImagenField;
        
        private InformacionMov[] movField;
        
        private MovimientoSrPack[] movSrPackField;
        
        private string idDocumentoClienteField;
        
        private string idDocumentoCliente2Field;
        
        private string placaField;
        
        private int idGPSField;
        
        private string formPagoField;
        
        private string nomProductoField;
        
        private string mensajeBuscarImagenField;
        
        private string motivoDevolucionField;
        
        private string mensajesValidacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaProbable
        {
            get
            {
                return this.fechaProbableField;
            }
            set
            {
                this.fechaProbableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumGui
        {
            get
            {
                return this.numGuiField;
            }
            set
            {
                this.numGuiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FecEnv
        {
            get
            {
                return this.fecEnvField;
            }
            set
            {
                this.fecEnvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int NumPie
        {
            get
            {
                return this.numPieField;
            }
            set
            {
                this.numPieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CiuRem
        {
            get
            {
                return this.ciuRemField;
            }
            set
            {
                this.ciuRemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NomRem
        {
            get
            {
                return this.nomRemField;
            }
            set
            {
                this.nomRemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DirRem
        {
            get
            {
                return this.dirRemField;
            }
            set
            {
                this.dirRemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CiuDes
        {
            get
            {
                return this.ciuDesField;
            }
            set
            {
                this.ciuDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NomDes
        {
            get
            {
                return this.nomDesField;
            }
            set
            {
                this.nomDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DirDes
        {
            get
            {
                return this.dirDesField;
            }
            set
            {
                this.dirDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int IdEstAct
        {
            get
            {
                return this.idEstActField;
            }
            set
            {
                this.idEstActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string EstAct
        {
            get
            {
                return this.estActField;
            }
            set
            {
                this.estActField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FecEst
        {
            get
            {
                return this.fecEstField;
            }
            set
            {
                this.fecEstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NomRec
        {
            get
            {
                return this.nomRecField;
            }
            set
            {
                this.nomRecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string NumCun
        {
            get
            {
                return this.numCunField;
            }
            set
            {
                this.numCunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Regime
        {
            get
            {
                return this.regimeField;
            }
            set
            {
                this.regimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Imagen
        {
            get
            {
                return this.imagenField;
            }
            set
            {
                this.imagenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=17)]
        public byte[] BytesImagen
        {
            get
            {
                return this.bytesImagenField;
            }
            set
            {
                this.bytesImagenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public InformacionMov[] Mov
        {
            get
            {
                return this.movField;
            }
            set
            {
                this.movField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        public MovimientoSrPack[] MovSrPack
        {
            get
            {
                return this.movSrPackField;
            }
            set
            {
                this.movSrPackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string IdDocumentoCliente
        {
            get
            {
                return this.idDocumentoClienteField;
            }
            set
            {
                this.idDocumentoClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string IdDocumentoCliente2
        {
            get
            {
                return this.idDocumentoCliente2Field;
            }
            set
            {
                this.idDocumentoCliente2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int IdGPS
        {
            get
            {
                return this.idGPSField;
            }
            set
            {
                this.idGPSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string FormPago
        {
            get
            {
                return this.formPagoField;
            }
            set
            {
                this.formPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string NomProducto
        {
            get
            {
                return this.nomProductoField;
            }
            set
            {
                this.nomProductoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string MensajeBuscarImagen
        {
            get
            {
                return this.mensajeBuscarImagenField;
            }
            set
            {
                this.mensajeBuscarImagenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string MotivoDevolucion
        {
            get
            {
                return this.motivoDevolucionField;
            }
            set
            {
                this.motivoDevolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string MensajesValidacion
        {
            get
            {
                return this.mensajesValidacionField;
            }
            set
            {
                this.mensajesValidacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servientrega.com/")]
    public partial class InfEnvios
    {
        
        private string numeroGuiaField;
        
        private string estadoEnvioField;
        
        private string motivoDevolucionField;
        
        private string fechaField;
        
        private string imagenField;
        
        private string observacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumeroGuia
        {
            get
            {
                return this.numeroGuiaField;
            }
            set
            {
                this.numeroGuiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EstadoEnvio
        {
            get
            {
                return this.estadoEnvioField;
            }
            set
            {
                this.estadoEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MotivoDevolucion
        {
            get
            {
                return this.motivoDevolucionField;
            }
            set
            {
                this.motivoDevolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Imagen
        {
            get
            {
                return this.imagenField;
            }
            set
            {
                this.imagenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImagenGuia", WrapperNamespace="http://servientrega.com/", IsWrapped=true)]
    public partial class ImagenGuiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servientrega.com/", Order=0)]
        public string strGuia;
        
        public ImagenGuiaRequest()
        {
        }
        
        public ImagenGuiaRequest(string strGuia)
        {
            this.strGuia = strGuia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImagenGuiaResponse", WrapperNamespace="http://servientrega.com/", IsWrapped=true)]
    public partial class ImagenGuiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servientrega.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ImagenGuiaResult;
        
        public ImagenGuiaResponse()
        {
        }
        
        public ImagenGuiaResponse(byte[] ImagenGuiaResult)
        {
            this.ImagenGuiaResult = ImagenGuiaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface wsRastreoEnviosSoapChannel : ServientregaApi.ServiceReference.wsRastreoEnviosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class wsRastreoEnviosSoapClient : System.ServiceModel.ClientBase<ServientregaApi.ServiceReference.wsRastreoEnviosSoap>, ServientregaApi.ServiceReference.wsRastreoEnviosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsRastreoEnviosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsRastreoEnviosSoapClient.GetBindingForEndpoint(endpointConfiguration), wsRastreoEnviosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsRastreoEnviosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsRastreoEnviosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsRastreoEnviosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsRastreoEnviosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsRastreoEnviosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.ArrayOfXElement> EstadoGuiaAsync(string ID_Cliente, string guia)
        {
            return base.Channel.EstadoGuiaAsync(ID_Cliente, guia);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InfEnvios[]> ConsultarGestionEntregasAsync(string Fecha, string Id_Cliente, string Id_Contacto, string Pwd)
        {
            return base.Channel.ConsultarGestionEntregasAsync(Fecha, Id_Cliente, Id_Contacto, Pwd);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.ArrayOfXElement> EstadoGuiasIdDocumentoClienteAsync(string ID_Cliente, string RelacionDocumentos)
        {
            return base.Channel.EstadoGuiasIdDocumentoClienteAsync(ID_Cliente, RelacionDocumentos);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InfEnvios[]> ConsultarGestionGuiasAsync(string sGuia, string Id_Cliente, string Id_Contacto, string Pwd)
        {
            return base.Channel.ConsultarGestionGuiasAsync(sGuia, Id_Cliente, Id_Contacto, Pwd);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InformacionGuiaMov> ConsultarGuiaAsync(string NumeroGuia)
        {
            return base.Channel.ConsultarGuiaAsync(NumeroGuia);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InformacionGuiaMov> ConsultarGuiaImagenAsync(string NumeroGuia, bool BuscarImagen)
        {
            return base.Channel.ConsultarGuiaImagenAsync(NumeroGuia, BuscarImagen);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InformacionGuiaMov> ConsultarGuiaExternoAsync(string NumeroGuia)
        {
            return base.Channel.ConsultarGuiaExternoAsync(NumeroGuia);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.ArrayOfXElement> EstadoGuiasAsync(string ID_Cliente, string RelacionGuias)
        {
            return base.Channel.EstadoGuiasAsync(ID_Cliente, RelacionGuias);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InfEnvios[]> ConsultarGestionDevolucionesAsync(string Fecha, string Id_Cliente, string Id_Contacto, string Pwd)
        {
            return base.Channel.ConsultarGestionDevolucionesAsync(Fecha, Id_Cliente, Id_Contacto, Pwd);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServientregaApi.ServiceReference.ImagenGuiaResponse> ServientregaApi.ServiceReference.wsRastreoEnviosSoap.ImagenGuiaAsync(ServientregaApi.ServiceReference.ImagenGuiaRequest request)
        {
            return base.Channel.ImagenGuiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.ImagenGuiaResponse> ImagenGuiaAsync(string strGuia)
        {
            ServientregaApi.ServiceReference.ImagenGuiaRequest inValue = new ServientregaApi.ServiceReference.ImagenGuiaRequest();
            inValue.strGuia = strGuia;
            return ((ServientregaApi.ServiceReference.wsRastreoEnviosSoap)(this)).ImagenGuiaAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServientregaApi.ServiceReference.InformacionGuiaMov> ConsultarGuiaPorNumeroReferenciaClienteAsync(string Id_Cliente, string Numero_Referencia)
        {
            return base.Channel.ConsultarGuiaPorNumeroReferenciaClienteAsync(Id_Cliente, Numero_Referencia);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaImagenNovedadesXMLAsync(string NumeroGuia, int IdProceso)
        {
            return base.Channel.ConsultarGuiaImagenNovedadesXMLAsync(NumeroGuia, IdProceso);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaEvidenciaRTImagenXMLAsync(string NumeroGuia)
        {
            return base.Channel.ConsultarGuiaEvidenciaRTImagenXMLAsync(NumeroGuia);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EstadoGuiaXMLAsync(string ID_Cliente, string guia)
        {
            return base.Channel.EstadoGuiaXMLAsync(ID_Cliente, guia);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGestionEntregasXMLAsync(string Fecha, string Id_Cliente, string Id_Contacto, string Pwd)
        {
            return base.Channel.ConsultarGestionEntregasXMLAsync(Fecha, Id_Cliente, Id_Contacto, Pwd);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EstadoGuiasIdDocumentoClienteXMLAsync(string ID_Cliente, string RelacionDocumentos)
        {
            return base.Channel.EstadoGuiasIdDocumentoClienteXMLAsync(ID_Cliente, RelacionDocumentos);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGestionGuiasXMLAsync(string Guia, string Id_Cliente, string Id_Contacto, string Pwd)
        {
            return base.Channel.ConsultarGestionGuiasXMLAsync(Guia, Id_Cliente, Id_Contacto, Pwd);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaXMLAsync(string NumeroGuia)
        {
            return base.Channel.ConsultarGuiaXMLAsync(NumeroGuia);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaImagenXMLAsync(string NumeroGuia, string BuscarImagen)
        {
            return base.Channel.ConsultarGuiaImagenXMLAsync(NumeroGuia, BuscarImagen);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EstadoGuiasXMLAsync(string ID_Cliente, string RelacionGuias)
        {
            return base.Channel.EstadoGuiasXMLAsync(ID_Cliente, RelacionGuias);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGestionDevolucionesXMLAsync(string Fecha, string Id_Cliente, string Id_Contacto, string Pwd)
        {
            return base.Channel.ConsultarGestionDevolucionesXMLAsync(Fecha, Id_Cliente, Id_Contacto, Pwd);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarGuiaPorNumeroReferenciaClienteXMLAsync(string Id_Cliente, string Numero_Referencia)
        {
            return base.Channel.ConsultarGuiaPorNumeroReferenciaClienteXMLAsync(Id_Cliente, Numero_Referencia);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultarInfoGuiasAsync(string NumerosGuias)
        {
            return base.Channel.ConsultarInfoGuiasAsync(NumerosGuias);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ConsultaGuiasGestionEntregaClienteAsync(string Id_Cliente, string Id_Contacto, string Pwd, string FechaInicial, string FechaFinal)
        {
            return base.Channel.ConsultaGuiasGestionEntregaClienteAsync(Id_Cliente, Id_Contacto, Pwd, FechaInicial, FechaFinal);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> FechaEntregaAsync(string NumeroGuia)
        {
            return base.Channel.FechaEntregaAsync(NumeroGuia);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsRastreoEnviosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsRastreoEnviosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsRastreoEnviosSoap))
            {
                // return new System.ServiceModel.EndpointAddress("http://sismilenio.servientrega.com.co/wsrastreoenvios/wsrastreoenvios.asmx");
                return new System.ServiceModel.EndpointAddress("https://sismilenio.servientrega.com.co/wsrastreoenvios/wsrastreoenvios.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsRastreoEnviosSoap12))
            {
                // return new System.ServiceModel.EndpointAddress("http://sismilenio.servientrega.com.co/wsrastreoenvios/wsrastreoenvios.asmx");
                return new System.ServiceModel.EndpointAddress("https://sismilenio.servientrega.com.co/wsrastreoenvios/wsrastreoenvios.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsRastreoEnviosSoap,
            
            wsRastreoEnviosSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "8.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
